CREATE TABLE IF NOT EXISTS clients (
    id BLOB NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    profile TEXT NOT NULL,
    redirect_uris TEXT NOT NULL,
    response_types TEXT NOT NULL,
    scopes TEXT NOT NULL,
    home_uri TEXT,
    logo_uri TEXT,
    contacts TEXT,
    policy_uri TEXT,
    tos_uri TEXT,
    jwks_uri TEXT,
    jwks TEXT,
    subject_type TEXT NOT NULL,
    sector_identifier_uri TEXT,
    id_token_signed_response_algorithm TEXT NOT NULL,
    id_token_encrypted_response_key_wrap TEXT,
    id_token_encrypted_response_content_encryption TEXT,
    software_id TEXT,
    software_version TEXT,
    created_at NUMERIC NOT NULL
)